#!/usr/bin/env bash

# -------------------------------------
# GIT ALIASES
# -------------------------------------

# See also: ~/.gitconfig

alias gf='git fetch --all'
alias gall='git add -A'
alias gs='git status'
alias gp='git push'
