# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# BREWFILE
# - https://github.com/Homebrew/homebrew-bundle
#
# Usage:
# brew bundle --file brew/Brewfile.work
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# -----
# Setup
# -----

cask_args appdir: "/Applications", require_sha: true

tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "heroku/brew"
tap "shopify/shopify"  

# ------------
# CLI Installs 
# ------------

brew "gcc"                          # https://formulae.brew.sh/formula/gcc
brew "gettext"                      # https://formulae.brew.sh/formula/gettext
brew "coreutils"                    # https://formulae.brew.sh/formula/coreutils
brew "curl"                         # https://formulae.brew.sh/formula/coreutils
brew "direnv"                       # https://formulae.brew.sh/formula/direnv
brew "git"                          # https://formulae.brew.sh/formula/curl
brew "jq"                           # https://formulae.brew.sh/formula/jq
brew "gh"                           # https://formulae.brew.sh/formula/gh
brew "heroku"                       # https://devcenter.heroku.com/articles/heroku-cli#install-the-heroku-cli
brew "openssl@3"                    # https://formulae.brew.sh/formula/openssl@3
brew "pipx"                         # https://formulae.brew.sh/formula/pipx
brew "pyenv"                        # https://formulae.brew.sh/formula/pyenv
brew "readline"                     # https://formulae.brew.sh/formula/readline
brew "ruby"                         # https://formulae.brew.sh/formula/ruby
brew "rbenv"                        # https://github.com/rbenv/rbenv
brew "ruby-build"                   # https://github.com/rbenv/rbenv
brew "vim"                          # https://formulae.brew.sh/formula/vim
brew "wget"                         # https://formulae.brew.sh/formula/wget
brew "xz"                           # https://formulae.brew.sh/formula/xz
brew "zlib"                         # https://formulae.brew.sh/formula/zlib
brew "zsh"                          # https://formulae.brew.sh/formula/zsh

# -----
# Casks 
# -----

cask "1password"                    # https://formulae.brew.sh/cask/1password
cask "discord"                      # https://formulae.brew.sh/cask/discord
cask "docker"                       # https://formulae.brew.sh/formula/docker
cask "firefox"                       # https://formulae.brew.sh/cask/firefox
cask "iterm2"                       # https://formulae.brew.sh/cask/iterm2
cask "kaleidoscope"                 # https://formulae.brew.sh/cask/kaleidoscope
cask "notion"                       # https://formulae.brew.sh/cask/notion
cask "postman"                      # https://formulae.brew.sh/cask/postman
cask "rectangle"                    # https://formulae.brew.sh/cask/rectangle
cask "slack"                        # https://formulae.brew.sh/cask/slack
cask "visual-studio-code"           # https://formulae.brew.sh/cask/visual-studio-code
cask "zoom"                         # https://formulae.brew.sh/cask/zoom
