#!/usr/bin/env bash

# -------------------------------------
# BASH ALIASES
# -------------------------------------

# Allow aliases to be with sudo
alias sudo="sudo "

# Navigation aliases
# =====================================

alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

alias repos="cd ~/Repos"
alias work="cd ~/Workspace"
alias prefs="cd ~/Repos/dotfiles"

# List dir aliases
# =====================================
# ref: http://ss64.com/osx/ls.html

alias ls="ls -G"
alias ll="ls -laG"
# Long form no user group, color
alias l="ls -oG"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Dev aliases
# =====================================

alias pcat="pygmentize -O style=monokai -f console256 -g"
function pless { pcat "$1" | less -r; }
alias cookiecutter-django="cookiecutter https://github.com/blitzagency/cookiecutter-django"

# Misc alises
# =====================================

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# IP addresses
alias ip="curl ipinfo.io/ip"
alias ipall="curl ipinfo.io/json"
alias localip="ipconfig getifaddr en0"

# Copy my public key to the pasteboard
function pubkey { more ~/.ssh/"${1}".pub | pbcopy && echo '=> Public key copied to pasteboard.\n'; }

# Flush DNS cache
alias flushdns="dscacheutil -flushcache"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Toggle Wallpaper Debug
alias wpdebugon="defaults write com.apple.dock desktop-picture-show-debug-text -bool TRUE;killall Dock"
alias wpdebugoff="defaults write com.apple.dock desktop-picture-show-debug-text -bool FALSE;killall Dock"

# Trash
function trash { mv "$1" ~/.Trash; }

# Run WP Scan
function wpscan { docker run -it --rm wpscanteam/wpscan --url "$1" --enumerate u1-1000; }

# Add ssh key
function ssh-add-all {
    ssh-add ~/.ssh/*_rsa
}
