#!/usr/bin/env bash

# -------------------------------------
# BASH PATHS
# -------------------------------------


declare -a prepend=(
    # Brew path, must preceed others
    # Path for python@2 is required to link python2/pip2 properly
    "/usr/local/bin"
    "/usr/local/opt/openssl/bin"
)

declare -a append=(
    "/usr/bin"
    "$HOME/bin"
)

for i in ${!prepend[*]}
do
    if [ -d ${prepend[$i]} ]; then
        PATH="${prepend[$i]}:$PATH"
    fi
done

for i in ${!append[*]}
do
    if [ -d ${append[$i]} ]; then
        PATH="$PATH:${append[$i]}"
    fi
done

unset prepend append

export PATH
