#!/usr/bin/env bash

# -------------------------------------
# BASH PATHS
# -------------------------------------


declare -a prepend=(
    # NOTE: Brew path, must preceed others.
    "/usr/local/bin"
    "/usr/local/sbin"
    "/usr/local/opt/openssl/bin"
    "/usr/local/opt/curl/bin"
    "/opt/chefdk/embedded/bin"
)

declare -a append=(
    "/usr/bin"
    "$HOME/bin"
    "$HOME/.poetry/bin"
)

for i in ${!prepend[*]}
do
    if [ -d ${prepend[$i]} ]; then
        PATH="${prepend[$i]}:$PATH"
    fi
done

for i in ${!append[*]}
do
    if [ -d ${append[$i]} ]; then
        PATH="$PATH:${append[$i]}"
    fi
done

unset prepend append

export PATH
