#!/usr/bin/env bash

# -------------------------------------
# BASH SETTINGS
# -------------------------------------

# Set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color

elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color

fi

# Enable bash completions if installed
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    source "$(brew --prefix)/etc/bash_completion"
fi

# Travis
# -------------------------------------

[ -f /Users/aubreytaylor/.travis/travis.sh ] && source "/Users/aubreytaylor/.travis/travis.sh"


# Pyenv
# -------------------------------------

export LDFLAGS="-L/usr/local/opt/sqlite/lib -L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/sqlite/include -I/usr/local/opt/zlib/include"

eval "$(pyenv init -)"

# Direnv
# -------------------------------------

eval "$(direnv hook bash)"
