#!/usr/bin/env bash

# -------------------------------------
# BASH SETTINGS
# -------------------------------------


# Set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color

elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color

fi

# Enable bash completions if installed
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    source "$(brew --prefix)/etc/bash_completion"
fi
