#!/usr/bin/env bash

# -------------------------------------
# SERVERLESSRC
# -------------------------------------

# From `serverless tabcompletion install`
# tabtab source for packages
# uninstall by removing these lines
[ -f ~/.config/tabtab/__tabtab.bash ] && . ~/.config/tabtab/__tabtab.bash || true