#!/usr/bin/env bash

# -------------------------------------
# DOCKER ALIASES
# -------------------------------------


function docker-stop { docker stop $(docker ps -q); }
function docker-images-prune { docker rmi $(docker images -q -f dangling=true); }
