#!/usr/bin/env bash

# -------------------------------------
# DOCKER ALIASES
# -------------------------------------


function docker-stop { docker stop $(docker ps -q); }
function docker-clean { docker rmi $(docker images -aq --filter dangling=true); }
