#!/usr/bin/env bash

# -------------------------------------
# NGROK INSTALL
# -------------------------------------

# -e, exit on error
# -u, unset variable is an error
# -o pipefail, fail pipe chain if error
set -eu -o pipefail

# See if ngrok exists, if not install
if test ! $(which ngrok); then
    echo "Installing Ngrok..."
    brew cask install ngrok
else
    echo "Ngrok already installed..."
fi

# token.private is a private file and _will not_ be in the VCS!
# Login to ngrok to get token
# See: https://dashboard.ngrok.com/user/login

token_file=$(dotfiles path ngrok token.private)

if [[ -e $token_file ]]; then
    token=$(head -n 1 $token_file)

    # This adds a folder ~/.ngrok2, which is not
    # managed because it's autogenerated by ngrok and contains
    # sensitive some information that's not easily obfuscated.
    ngrok authtoken "$token"
else
    # will dump error from dotfiles path
    echo "$token_file"
    exit 1
fi
