#!/usr/bin/env bash

# -------------------------------------
# PIPENV RC
# -------------------------------------
# SEE: https://docs.pipenv.org/advanced/#configuration-with-environment-variables

export PIPENV_VENV_IN_PROJECT=True
export PIPENV_SHELL_FANCY=True
export PIPENV_IGNORE_VIRTUALENVS=True
